export var SECTION_ALIGNMENT_OPTION;
(function (SECTION_ALIGNMENT_OPTION) {
  SECTION_ALIGNMENT_OPTION['LEFT'] = 'left';
  SECTION_ALIGNMENT_OPTION['CENTER'] = 'center';
  SECTION_ALIGNMENT_OPTION['RIGHT'] = 'right';
})(SECTION_ALIGNMENT_OPTION || (SECTION_ALIGNMENT_OPTION = {}));
export var SECTION_IMAGE_PLACEMENT;
(function (SECTION_IMAGE_PLACEMENT) {
  SECTION_IMAGE_PLACEMENT['LEFT'] = 'left';
  SECTION_IMAGE_PLACEMENT['RIGHT'] = 'right';
})(SECTION_IMAGE_PLACEMENT || (SECTION_IMAGE_PLACEMENT = {}));
export var SECTION_MEDIA_TYPE;
(function (SECTION_MEDIA_TYPE) {
  SECTION_MEDIA_TYPE['NONE'] = 'NONE';
  SECTION_MEDIA_TYPE['IMAGE'] = 'IMAGE';
  SECTION_MEDIA_TYPE['VIDEO'] = 'VIDEO';
})(SECTION_MEDIA_TYPE || (SECTION_MEDIA_TYPE = {}));
export var SECTION_MEDIA_SIZE;
(function (SECTION_MEDIA_SIZE) {
  SECTION_MEDIA_SIZE['SMALL'] = 'small';
  SECTION_MEDIA_SIZE['LARGE'] = 'large';
})(SECTION_MEDIA_SIZE || (SECTION_MEDIA_SIZE = {}));
