name: Protect Sample Data

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'apps/sanity/sample-data.tar.gz'
      - '.github/workflows/protect-sample-data.yml'

  # Allows triggering this workflow from GitHub UI
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-sample-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check sample data modifications 🔒
        id: check-sample-data
        run: |
          # Get the list of files changed in the PR
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})

          # Check if sample-data.tar.gz was modified
          if echo "$CHANGED_FILES" | grep -q "apps/sanity/sample-data.tar.gz"; then
            # Get the author of the PR
            PR_AUTHOR="${{ github.event.pull_request.user.login }}"
            # Get the repository owner
            REPO_OWNER="${{ github.repository_owner }}"

            if [ "$PR_AUTHOR" != "$REPO_OWNER" ]; then
              echo "::error::Sample data file modification requires approval from the repository owner."
              echo "::error::Please contact @$REPO_OWNER for approval."
              exit 1
            else
              echo "::warning::Sample data file modified by repository owner. Proceeding with caution."
            fi
          fi

      - name: Comment on PR 💬
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ **Sample Data Protection**\n\nThis PR modifies the sample data file (\`apps/sanity/sample-data.tar.gz\`). For security reasons, only the repository owner can modify this file.\n\nPlease contact @${{ github.repository_owner }} for approval.`
            })
